### ISSUE TITLE
Updates to README to make this site more accessible.

### ISSUE THREAD

**Issue by melodykramer** [18F/Course-Change#1]
Doing a bit of spring cleaning on our repos this week to check for clarity and accessibility and have a quick question:

Does this program live somewhere else now? If so, I'm happy to point people to the location. If not, I'd like to add a note that says this program is not currently in development - so users aren't confused.

**Comment by gbinal** [comment]
Thanks, @melodykramer.  I'm going to go ahead and delete this repo.  The idea behind it never got off the ground.
